version: "3.7"

services:

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        XDEBUG_PORT: ${XDEBUG_PORT:-9001}
        USER_UID: ${USER_UID:-1000}
        USER_NAME: ${USER_NAME:-dockeruser}
    container_name: '${PROJECT_NAME}-app'
    working_dir: /var/www
    restart: always
    depends_on:
        - mysql
    volumes:
      - .:/var/www
    environment:
      DOCKER_UID: 1000
      DOCKER_GID: 1000
      XDEBUG_CONFIG: 'client_host=172.17.0.1 client_port=9001'
      XDEBUG_MODE: 'debug'
      PHP_IDE_CONFIG: 'serverName=auto-clear.test' # domain name

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: '${PROJECT_NAME}-nginx'
    working_dir: /var/www
    restart: always
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '88:80'
    depends_on:
      - app

  mysql:
    image: mysql:latest
    container_name: '${PROJECT_NAME}-mysql'
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3308:3306'
    expose:
      - 3308
    volumes:
      - ./docker/mysql:/var/lib/mysql
